// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_user_id_ from "./routes/[user_id].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $countdown from "./routes/countdown.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $html from "./routes/html.tsx";
import * as $index from "./routes/index.tsx";
import * as $page from "./routes/page.tsx";
import * as $plain from "./routes/plain.tsx";
import * as $search from "./routes/search.tsx";
import * as $sub_special from "./routes/sub/special.tsx";
import * as $subscribe from "./routes/subscribe.tsx";
import * as $Countdown from "./islands/Countdown.tsx";
import * as $Counter from "./islands/Counter.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[user_id].tsx": $_user_id_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/api/joke.ts": $api_joke,
    "./routes/countdown.tsx": $countdown,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/html.tsx": $html,
    "./routes/index.tsx": $index,
    "./routes/page.tsx": $page,
    "./routes/plain.tsx": $plain,
    "./routes/search.tsx": $search,
    "./routes/sub/special.tsx": $sub_special,
    "./routes/subscribe.tsx": $subscribe,
  },
  islands: {
    "./islands/Countdown.tsx": $Countdown,
    "./islands/Counter.tsx": $Counter,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
